---
# Install PostgreSQL and repmgr
#- import_tasks: install.yml

# Configure PostgreSQL for replication
#- import_tasks: postgresql_config.yml
#
# Configure repmgr
- import_tasks: repmgr_config.yml
#
## Setup primary or standby node based on role
- import_tasks: primary_setup.yml
  when: pg_role == 'primary'
#
- import_tasks: standby_setup.yml
  when: pg_role == 'standby'