---
# Configure repmgr

- name: Create repmgr configuration directory
  file:
    path: "{{ repmgr_conf_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true

- name: Create repmgr log directory
  file:
    path: "{{ repmgr_log_file | dirname }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true

- name: Create repmgr pid directory
  file:
    path: "{{ repmgr_pid_file | dirname }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true

- name: Configure repmgr.conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_config_file }}"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true

- name: Create repmgr service file
  template:
    src: repmgr.service.j2
    dest: /etc/systemd/system/repmgr.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: reload systemd

- name: Enable repmgr service
  systemd:
    name: repmgr
    enabled: yes
    daemon_reload: yes
  become: true